Smithsonian/dpo-voyager

source/client/components/CVARManager.ts

New version of Chrome requires we confirm the gl context is xr compatible.

Bug fix to make gl context XR compatible

---

source/client/io/ModelReader.ts
source/client/shaders/UberPBRMaterial.ts

So I noticed the `UberPBRMaterial` was missing the emissive map from one of my models.
I checked why and found `UberPBRMaterial.copyStandardMaterial()`was simply not copying it.
Instead of just adding it I wondered if other properties were missed in the copy and it turns out a whole bunch of them were.
The native `Material.copy()`method from THREE (code [here](https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L404)) seems to do the job, with the added benefit of being maintained upstream.
I tested it on my models and it looked right, fixing the missing emissive and not breaking anything. i'd like to know if it breaks anything for you, or if  you would rather only include the required properties in `copyStandardMaterial`.

use native Material.copy method

---

source/client/components/CVLanguageManager.ts

- load the UI in french (using a query string or custom-element attribute)
- load a scene set-up to be in english (`setups[0].language.language = "EN"`in the scene file)
The language widget shows the scene as **english**, but it's (sometimes) displayed in french.
It is the result of a race condition: The french dictionary is requested before the document, then if it loads after the setup has been parsed, it changes back the output language.
This commit fixes it.

fix a race condition in CVLanguageManager

---

source/client/ui/explorer/ContentView.ts

in scenes where readerVisible == true, `<sv-action-prompt>` doesn't get rendered and `CVOrbitNavigation.tick()` then throws an error when trying to modify the prompt's style.
I choose to always disable the prompt when the reader is visible. Another choice might be to keep it when `readerPosition !== EReaderPosition.Overlay`.

fix bad value for promptVisible when readerVisible == true

---

source/client/applications/StoryApplication.ts

the previous order of operations would cause a request to be fired to the wrong URL if `root` is set to something other than `/<scene_name>`(eg. a `scenes` subfolder).

Fix #252 set mediaManager.rootUrl before calling baseUrlValid

---

source/client/io/JSONWriter.ts

If for whatever reason `JSONWriter` fails to put the updated document, it causes loadingManager to be indefinitely busy.
This change properly registers the failure.

register error in loadingManager when JSONWriter.put fails

---

source/client/ui/PropertyBoolean.ts
source/client/ui/PropertyColor.ts
source/client/ui/PropertyEvent.ts
source/client/ui/PropertyNumber.ts
source/client/ui/PropertyOptions.ts
source/client/ui/PropertySlider.ts
source/client/ui/PropertyString.ts
source/client/ui/explorer/styles.scss
source/client/ui/story/PropertyView.ts
source/client/ui/story/SettingsTaskView.ts
source/client/ui/story/styles.scss

So, following up on #257 was something of a rabbit hole.
**TL:DR:** Those changes removes ~1000 lines of hard-to-maintain code while providing the following :
- Hex/HSV/RGB color notation support for color selection, working everywhere (native color picker)
- all-or-nothing wrap for groups of number (uses `@container` when available, gracefully degrade to an ugly wrap otherwise)
- uniform styling across Explorer/Story applications for input colors and styles
- clear visual indicator for boolean properties or options properties.
**Long version :**
Turns out there were (kind of) 3 systems, none of them working in every case:
- `<ff-property-view>` : general purpose custom built do-it-all input component for `voyager-story`
- `<sv-property-view>` : more limited version of the former. Uses …

remove all references to ff-property-view and ff-property-field. Fix #257

---

source/client/schema/common.ts

A German colleague pointed out a small grammatical error for the ui pop-up to switch to the german language version of her voyager. It should be German (Deutsch) instead of German (Deutsche). I will also ask her to update the german language interface accessibility.

grammatical correction from Deutsche to Deutsch

---

source/client/ui/story/ArticleEditor.ts
source/client/ui/story/editor_css/overrides.css
source/client/ui/styles.scss

`max-width` was already set in [styles.scss#L83](https://github.com/Smithsonian/dpo-voyager/blob/master/source/client/ui/styles.scss#L83), but not in editor leading to inconsistent behaviour.
Moreover, max-width without `height: auto` leads to stretched images.
I created a new css file because the current `content.ui.min.css`and `content.min.css` seems directly imported from tinyMCE and keeping them pristine will probably help future updates.
With those changes it is still possible to manually force images to stretch by specifying a different `height` in the image block popup.

set max-width to 100% and height to auto

---

source/client/components/CVAnnotationView.ts
source/client/components/CVAnnotationsTask.ts
source/client/components/CVArticlesTask.ts
source/client/components/CVAudioTask.ts
source/client/components/CVLanguageManager.ts
source/client/components/CVMeta.ts
source/client/components/CVTaskProvider.ts
source/client/components/CVToursTask.ts
source/client/ui/PropertyOptions.ts
source/client/ui/explorer/styles.scss
source/client/ui/story/AnnotationsTaskView.ts
source/client/ui/story/ArticlesTaskView.ts
source/client/ui/story/AudioTaskView.ts
source/client/ui/story/CollectionPanel.ts
source/client/ui/story/TourPanel.ts
source/client/ui/story/ToursTaskView.ts

I did a bunch of work trying to bring the multi-language support to a point where non-english speakers and particularly non-primarily-english scenes have a smooth experience.
**There was a number of issues:**
- In a number of places, `ELanguageType.EN` was used interchangeably with `DEFAULT_LANGUAGE`. The fix is straightforward. `ELanguageType.EN` now used as a default only where it makes sense.
- I removed every individual task's `ins.language` property. They were the source of a number or race conditions, while barely used in the code and I found it easier to remove them and use `CVLanguageManager`as the unique source of language state everywhere. This should also help avoid regressions in the future.
**Some backward-compatible changes : **
- Fixing a race condition where the scene's …

Better other default language support

---

source/client/components/CVDocument.ts
source/client/ui/story/CollectionPanel.ts

The document's `asset.copyright` field is currently always erased on save : the value is hardcoded in `CVDocument`.
I'd like it to be kept the same through saves as we have multiple sources that have different copyright requirements. A scene modification shouldn't change this field.
Additionally, I'd like to be able to edit the notice in the UI so I propose to add a text field in the collection panel. But maybe that's just me and this would be undesirable for everyone else? I'm OK handling this outside of voyager if necessary as long as it don't get replaced after each scene change.

Keep Copyright notices

---

source/client/ui/PropertyColor.ts
source/client/ui/explorer/styles.scss

This PR reintroduces `<ff-color-edit>` instead of the native `<input type="color">` to solve accessibility issues.
I more or less copied-back the original implementation that existed before https://github.com/Smithsonian/dpo-voyager/pull/259 with a few changes:
- some styles updates (minor)
- use a `pickerActive` reactive property instead of forcing requestUpdate (more concise)
- Register `document.addEventListener("click",/* */)` to close picker when clicking somewhere else only when picker is active (small performance optimization)
- Add shortcut `Enter` to close picker
Sorry for the long delay in fixing this and more generally for the inconvenience caused by https://github.com/Smithsonian/dpo-voyager/pull/259, I clearly didn't test it enough before submitting.

add back ff-color-edit popup. Fix #257

---

libs/ff-scene/source/components/CCamera.ts
libs/ff-scene/source/components/CObject3D.ts
libs/ff-three/source/Floor.ts
libs/ff-three/source/Grid.ts
libs/ff-three/source/HTMLSprite.ts
libs/ff-three/source/UniversalCamera.ts
package-lock.json
package.json
source/client/annotations/AnnotationSprite.ts
source/client/components/CVAnnotationView.ts
source/client/components/CVAssetReader.ts
source/client/schema/document.ts
source/client/schema/model.ts
source/client/shaders/UberPBRAdvMaterial.ts
source/client/shaders/UberPBRMaterial.ts
source/client/shaders/uberPBRShader.frag
source/client/shaders/uberPBRShader.vert

I needed an update to three.js to test https://github.com/mrdoob/three.js/pull/27098 from r161 so I thought I might as well make a PR for it.
There was some uninteresting types rewrites, some frag/vert updates that I extracted from a diff of the physical shader from r158 to r168. I only used this in local tests so it might break in unexpected ways.

update-in-place for three r168

---

libs/ff-core/source/Color.ts
libs/ff-core/test/Color.test.ts
source/client/schema/model.ts
source/client/ui/PropertyColor.ts
source/client/ui/explorer/styles.scss

First commit implements the text input. It looks like this : 
Then I wanted to test the various input formats. For reference, `@ff/core/Color` is able to parse  3-6 chars hex, `rgb()`, `hsl()` notations. All of which are parsed OK, though they get auto-converted to 6-chars hex immediately. Dealing with this would probably require storing some internal string-state inside the `Color` class but would still be lost on save. Let me know if you think it's needed.
Then I wanted to test rgba notations. I noticed no property currently use rgba. There is `Material.BaseColor` from **CVModel2** that is mapped to a Vector4, but the error is the other way around: It gets assigned to a `THREE.Color` that have no alpha. I fixed that in 7073d361c9b16598f4aed8ccf4f2db29aaf425a7.
I still temporarily …

allow pasting color hex codes in sv-property-color. Fix #303

---

libs/ff-core/source/Publisher.ts

Stumbled upon this working on something else and I thought I should patch it :
Fixes `Publisher.emit()` that returned `void` instead of `boolean` and accepted `any` values for both parameters.
Return value wasn't used outside of CHierarchy in a routine I'm not sure is even needed, but the signature is consistent with Node's [EventEmitter.emit](https://nodejs.org/api/events.html#emitteremiteventname-args) so we should keep it this way.

fix types for Publisher.emit

---

source/client/ui/PropertyNumber.ts
source/client/ui/explorer/styles.scss
source/client/ui/story/PropertyView.ts

Continuing my crusade against broken data bindings.
Properties that have their values linked from another prop should probably not be interactive.
Because the link is unidirectional, the value change is not propagated and it leads to inconsistencies.
The only case where this is currently visible is with the Lights transform, when `lightsFollowCam` is enabled. If I change this value, it's ignored the next time I move the camera.
This is a very minor annoyance but if this gets merged I intend to use such a binding to control the **transform** inputs of **CVCamera**, thus allowing the camera's transform setting to be locked-up, fixing #314.
See https://github.com/Smithsonian/dpo-voyager/commit/4bab99f17e9f7fee4ac8995444e7f19c4c088a43 for changes that would be required to link Cameras …

prevent interacting with linked Property

---

libs/ff-three/source/HTMLSprite.ts
libs/ff-three/source/HTMLSpriteGroup.ts
source/client/annotations/CircleSprite.ts
source/client/annotations/ExtendedSprite.ts
source/client/annotations/StandardSprite.ts

`HTMLSprite.renderHTMLElement` and `HTMLSpriteGroup.render` were causing unnecessary forced reflows within their render loops.
skipping `getBoundingClientRect()` where possible solves it.
Basically free performance gain, about .5 ms per annotation.

Eliminate forced reflows when rendering HTMLSprites

---

source/client/applications/ExplorerApplication.ts
source/client/applications/MiniApplication.ts
source/client/applications/StoryApplication.ts

`ExplorerApplication.evaluateProps()` won't yield the same result when run twice, because `const props = this.props` only references the original object, so down the line when we get the queryString values, it changes the values stored in `this.props`, thus potentially changing the result of `evaluateProps()` in unexpected ways.
I think we should keep `this.props` unchanged or make it clear we intend to modify it by removing the `const props = this.props` assignment.
I prefer the first solution as it's a one-line change and allows calling evaluateProps after a change in the page's queryString.

make evaluateProps reentrant in all applications

---

source/client/applications/ExplorerApplication.ts
source/client/components/CVLanguageManager.ts

remove bad check for language value. Find another way to force language from queryString
wasn't working properly since https://github.com/Smithsonian/dpo-voyager/pull/280 because of a dumb mistake of mine.
Forcing the language from `props` in `postLoadHandler` should work everytime, while allowing the value from `scene.setup.language` to be used when applicable.

fix language initialization from scene.setup

---

source/client/components/CVAssetManager.ts
source/client/components/CVAssetReader.ts
source/client/components/CVModel2.ts
source/client/io/ModelReader.ts
source/client/models/Derivative.ts

Fixes #325 and #326 with proper LoadingManager usage.
In the end it's arguably better than before because GLTFLoader counts 1 "item" per GLTF buffer, which generally doesn't make much sense and is a bit too verbose to my taste.
a581341bf5564cfbf0d4b129db2fba36978b4d60 in particular _may_ lead to some unexpected results : Those kind of algorithms are always a bit tricky to get right.

Model load refactor

---

source/client/io/ModelReader.ts

Specifically [BufferGeometry.computeBoundingBox](https://threejs.org/docs/?q=Mesh#api/en/core/BufferGeometry.computeBoundingBox), which sets `BufferGeometry.boundingBox`, looks like it is not used anywhere.
The code uses [computeLocalBoundingBox](https://github.com/Smithsonian/dpo-voyager/blob/dff5bcf0425c2c4b0ec79c0ed3ef8afc2b30d793/libs/ff-three/source/helpers.ts#L106), using more or less the same algorithm but with additional tree traversal and matrix composition logic.
fwiw, each of those can take up to 100ms to compute on large-ish models so it can add up quickly. Ideally i'd totally skip this if the box can be retrived from the svx document or at least compute only the **Thumb** model's box and roll with it, but that'd be a more substantial change for another time.

deduplicate models bounding box computation

---

libs/ff-scene/source/assets/WebDAVProvider.ts

Setting up the default WebDAV server, if you create a folder (`cube` in my example) with a dummy scene with it and navigate to `http://localhost:8000/voyager-story-dev.html?document=/cube/scene.svx.json` **WITHOUT** setting the `root` parameter, the scene kinda works but for the asset tree not matching properly.
Easiest way to show this is click `Create` in the Article Task. Nothing is shown until you click somewhere to deselect said article.
I traced it back to `WebDAVProvider.rootPath`, being normally set to `/cube/` but defaults to the value of `ExplorerApplication.props.document`,  here `/cube/scene.svx.json`.
I checked usage of this path and it looks like it's only used in `WebDAVProvider.parseResponse`
Not sure if expecting `rootPath` to always end with a trailing "/" is a valid …

ensure WebDAVProvider.rootPath is a folder

---

libs/ff-graph/source/components/CPulse.ts
libs/ff-scene/source/components/CRenderer.ts
package-lock.json
source/client/applications/coreTypes.ts
source/client/components/CVDerivativesController.ts
source/client/components/CVDerivativesTask.ts
source/client/components/CVModel2.ts
source/client/components/CVSetup.ts
source/client/components/CVSlicer.ts
source/client/components/CVTask.ts
source/client/io/GeometryReader.ts
source/client/io/ModelReader.ts
source/client/models/Derivative.ts
source/client/models/DerivativeList.ts
source/client/ui/explorer/ContentView.ts
source/client/webpack.config.js
source/test/components/CVDerivativesController.test.ts
source/test/tsconfig.json
source/test/webpack.config.js

So there is this idea_ I worked on for the past few months that makes it possible to open a ~200 models scene with each model having a 4k diffuse (in `High` quality) on a mobile device. 
It's still a very rough prototype but I wanted to share it and begin discussions on what requirements we'd have to meet for this to get merged into voyager.
This branch temporarily includes https://github.com/Smithsonian/dpo-voyager/pull/266 to allow more camera mobility  and a lot of performance patches that should be (or have been) extracted to their own PRs. It also needs  to be rebased on Voyager's latest release. I'll do all this down the line as I clean everything up.
A working example is visible there: 
https://lodtest.ecorpus.holusion.net/ui/scenes/Lascaux_retake2/view
Same model, without LOD …

Dynamic LOD switching

---

source/client/components/CVArticlesTask.ts
source/client/components/CVMeta.ts

Some article languages troubles that —as far as I know— only happens when reloading a document.
- d4381d4c04822dabf7d4e06c7e707e919c19c929 : In a normal sequence, `CVReader.updateLanguage()` is triggered first in English, then `CVReader.updateArticles()` then (if necessary) `CVReader.updateLanguage()` again if scene language is not english. When reloading a scene, the active language doesn't change so the article's languages are out of sync. I think the best solution is to initialize the articles using `CVLanguageManager.outs.language` so this won't happen.
- 11fe7f631812ae393cd990585fd8a63e04421222 Article editor wasn't updated when reloading the scene. Since selection is reset, it should be reset too. Since its update is conditional, we just have to force-update `ins.edit` to trigger …

Articles languages on reloadDocument
